name: CI

on:
    push:
        branches:
            - master
            - tests

    pull_request:
        branches:
            - master

jobs:
    test_and_analyze:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]

        steps:
            - uses: actions/checkout@v3

            - name: Setup Python
              uses: actions/setup-python@v3
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements-dev.txt
                  pip install -e .

            - name: Static analysis (mypy)
              run: mypy

            - name: Run tests
              run: pytest
